config/routes.rb
CheerupsApp::Application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks"}
  devise_for :users
  
  root to: "cheerups#index"
  resources :users
  resources :cheerups

  resources :cheerups do
    member do
      put 'vote/:direction', to: 'cheerups#vote', as: 'vote'
    end

    collection do 
      match 'search'=> "cheerups#search" , via: [:get, :post] , as: :search  
      get 'display/:display', to: 'cheerups#display', as: 'display'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :confirmable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:facebook] 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  :name, :user_name , :status, :profile_picture, :remote_profile_picture_url, :prominence, :reputation, :role
  
  include Gravtastic
   gravtastic size: 75, default: "retro", secure: true 

  mount_uploader :profile_picture, ProfilePictureUploader

  validates :name, presence: true, allow_blank: false
  validates :user_name, presence: true, allow_blank: false
  validates :user_name, uniqueness: true

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
    
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.first_name
      user.user_name = auth.info.email
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      
      #user.name = auth.info.name  # assuming the user model has a name
      user.profile_picture = auth.info.image 
      # assuming the user model has an image
      # raise
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


  has_many :cheerups , dependent: :destroy

  acts_as_voter

  def can_destroy?
    # user can destroy himself or 
    # admin user can destroy anyone only until 1 admin user is left 
    if self.role == 'user' 
      return true
    elsif self.role == 'admin'
       return true if User.find_all_by_role("admin").count > 1
    else
      return false
    end
  end

  
  def calc_prominence
    cheerups.pluck(:prominence).sum
  end

  def set_prominence
    self.update_attributes(prominence: self.calc_prominence)
  end

  def self.sort_by_prominence
    User.all.sort_by(&:prominence).reverse
  end

  def update_reputation
    case
    when prominence > 10 && prominence <= 50
      reputation = 'Senior_Cheerupper'
    when prominence > 50
      reputation = 'Master_Cheerupper'
    when prominence < 0 && prominence >= -10
      reputation = 'Junior_Dragdowner'
    when prominence < -10 && prominence >= -50
      reputation = 'Senior_Dragdowner'
    when prominence < -50
      reputation = 'Master_Dragdowner'
    else
      reputation = 'Junior_Cheerupper'
    end

    self.update_attributes(reputation: reputation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource  except: :create_test_users_data
  before_filter :authenticate_user! , except: :create_test_users_data


  def index
    @users = User.sort_by_prominence
    respond_to do |format|
      format.html 
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy

    @user = User.find(params[:id])
    if @user.can_destroy?
      @user.destroy
    else
      flash[:notice] = 'Can Not delete the admin user.' 
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :name
    = f.text_field :name, autofocus: true
  %div
    = f.label :user_name
    = f.text_field :user_name
  %div
    = f.label :email
    = f.text_field :email
  %div
    = f.label :profile_picture
    = f.file_field :profile_picture
  .submit_form_button
    = f.submit
  %div
    = link_to content_tag('a', '', class: 'icon-trash'), @user, confirm: "Are you sure you want to delete '#{@user.name}' forever and ever?", method: :delete

app/views/users/edit.html.haml
%h1#welcome Edit user
= render 'form'

app/views/users/index.html.haml
%table.table-minimal
  %tr
    / %th Picture
    / %th Name
    / %th Username
    / %th Email
    / %th Prominence
    / %th Reputation
    / %th
    / %th
  - @users.each do |user|
    %tr
      
    %td 
      - if user.profile_picture?
        = link_to image_tag(user.profile_picture.thumb.url), user.profile_picture.detail.url  
      - else
        = link_to image_tag user.gravatar_url
      %td= user.name
      %td= user.user_name
      %td= user.email
      %td= user.prominence
      %td= user.reputation
         
      %td= button_to "Show", user, :method => "get"
      - if current_user && current_user.role?(:admin)
        %td= link_to "Edit", edit_user_path(user), :method => "get"
        %td= link_to 'Delete account', user, confirm: "Are you sure you want to delete '#{user.name}' forever and ever? You cannot undo this action", method: :delete
%br

app/views/users/new.html.haml
%h1#welcome New user

= render 'form'

app/views/users/show.html.haml
.show-user-header
  %ul
    - if @user.profile_picture?
      %li= link_to image_tag(@user.profile_picture.thumb.url), @user.profile_picture.detail.url  
    - else
      %li= image_tag @user.gravatar_url  

    %li
      = @user.name

.profile_info
  %p
    %span Username:
    = @user.user_name
  %p
    %span Email: 
    = @user.email
  %p
    %span Prominence:
    = @user.prominence
  %p
    %span Reputation:
    = @user.reputation

%main#cheerup_main

  #cheerups
    %h5#user-cheerups Cheerups
    - @user.cheerups.each do |cheerup|
      .cheerup
        .cheerup_content
          - if cheerup.cheerup_image?
            = link_to image_tag(cheerup.cheerup_image.thumb.url), cheerup.cheerup_image.detail.url
          - else
            %p= cheerup.content
          .prominence{:id =>"prominence_#{cheerup.id}"} 
            = cheerup.prominence

          .cheerup-show
            = link_to cheerup do
              %i{class:"fa fa-search-plus"}
        .cheerup_poster_info 
          %ul
            - if cheerup.user.profile_picture?
              %li= link_to image_tag(cheerup.user.profile_picture.thumb.url), cheerup.user, class: 'cheerup-avatar'  
            - else
              %li= link_to image_tag(cheerup.user.gravatar_url), cheerup.user, class: 'cheerup-avatar'   

            %li
              = link_to cheerup.user.try(:user_name), cheerup.user
              = "#{time_ago_in_words(cheerup.created_at)} ago"
            
            %li.downvotes{:id =>"downvote_#{cheerup.id}"}
              - if current_user
                - if  session['warden.user.user.key'][0][0].to_i != cheerup.user_id
                  = link_to vote_cheerup_path(cheerup, direction: 'down'), method: :put, :id => "downvote_#{cheerup.id}" do
                    %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
                - else
                  %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
              - else
                %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
            %li.upvotes{:id =>"upvote_#{cheerup.id}"}
              - if current_user
                - if  session['warden.user.user.key'][0][0].to_i != cheerup.user_id
                  = link_to vote_cheerup_path(cheerup, direction: 'up'), method: :put, :id => "upvote_#{cheerup.id}" do
                    %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_upvotes.size}
                - else
                  %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_upvotes.size}
              - else
                %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_downvotes.size}
        - if current_user
          - if  session['warden.user.user.key'][0][0].to_i == cheerup.user_id
            .cheerup_admin_panel
              %ul
                %li= link_to 'Edit', edit_cheerup_path(cheerup)
                %li= link_to 'Delete', cheerup, method: :delete, data: { confirm: 'Are you sure?' }    
%br
- if current_user
  - if  session['warden.user.user.key'][0][0].to_i == @user.id
    = link_to 'Edit', edit_user_path(@user) 

    = link_to 'Delete account', @user, confirm: "Are you sure you want to delete '#{@user.name}' forever and ever? You cannot undo this action", method: :delete