config/routes.rb
CheerupsApp::Application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks"}
  devise_for :users
  
  root to: "cheerups#index"
  resources :users
  resources :cheerups

  resources :cheerups do
    member do
      put 'vote/:direction', to: 'cheerups#vote', as: 'vote'
    end

    collection do 
      match 'search'=> "cheerups#search" , via: [:get, :post] , as: :search  
      get 'display/:display', to: 'cheerups#display', as: 'display'
    end
  end
end

app/models/cheerup.rb
class Cheerup < ActiveRecord::Base

  attr_accessible :content, :cheerup_image, :created_at, :updated_at, :prominence
  mount_uploader :cheerup_image, CheerupImageUploader

  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true
  validates_length_of :content, maximum: 141

  acts_as_votable

  def calc_prominence
    upvotes = get_upvotes.size
    downvotes = get_downvotes.size
    upvotes - downvotes
  end

  def set_prominence
    self.update_attributes(prominence: self.calc_prominence)
  end

  def self.sort_by_prominence
    Cheerup.all.sort_by(&:prominence).reverse
  end


  

  def self.random_display
    Cheerup.all.shuffle
  end

end

app/controllers/cheerups_controller.rb
class CheerupsController < ApplicationController

  load_and_authorize_resource :except => [:index, :search]

  before_filter :authenticate_user!, except: [:index, :show, :search, :display]

  def search
    @cheerup = Cheerup.new
    @cheerups = @result
    render "index"
  end

  def index
    #raise
    @cheerups = Cheerup.random_display
    @cheerup = Cheerup.new

    respond_to do |format|
      format.html 
      format.json { render json: @cheerups }
    end
  end

  def show
    @cheerup = Cheerup.find(params[:id])
    #raise
      respond_to do |format|
      format.html
      format.json { render json: @cheerup }
    end
  end

  def display
    @cheerup = Cheerup.new
    #raise
    case params[:display]
    when 'random'
      @cheerups = Cheerup.random_display
    when 'prominent'
      @cheerups = Cheerup.sort_by_prominence
    end
    render 'index'
  end


  def new
    @cheerup = Cheerup.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @cheerup }
    end
  end

  def create
    @cheerup = Cheerup.new(params[:cheerup])
    @cheerup.user = current_user

    respond_to do |format|
      if @cheerup.save
        format.html { redirect_to cheerups_path, notice: 'Cheerup was successfully created.' }
        format.json { render json: @cheerup, status: :created, location: @cheerup }
      else
        format.html { render action: "new" }
        format.json { render json: @cheerup.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @cheerup = Cheerup.find(params[:id])
  end

  def update
    @cheerup = Cheerup.find(params[:id])

    respond_to do |format|
      if @cheerup.update_attributes(params[:cheerup])
        format.html { redirect_to @cheerup, notice: 'Cheerup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cheerup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

   @cheerup = Cheerup.find(params[:id])
   @cheerup.destroy

   respond_to do |format|
     format.html { redirect_to cheerups_url }
     format.json { head :no_content }
   end
 end  


  def vote
    @cheerup = Cheerup.find(params[:id])

    respond_to do |format|
      if @cheerup.user != current_user
        case params[:direction]
        when 'up'
          @cheerup.liked_by current_user
        when 'down'
          @cheerup.downvote_from current_user
        end

        @cheerup.set_prominence
        @cheerup.user.set_prominence

        format.html { redirect_to cheerups_path }
        format.json { head :no_content}
      else
        format.html { redirect_to cheerups_path, notice: "Sorry, you can't vote on your own cheerup" }
        format.json { render json: "Sorry, you can't vote on your own cheerup", status: :unprocessable_entity }
      end
    end
  #   @cheerup.set_prominence
  #   @user.set_prominence
  #   @user.update_reputation
  #   redirect_to cheerups_path
  # else
  #   redirect_to cheerups_path, notice: "Sorry, you can't vote on your own cheerup"

   end
  
end

app/helpers/cheerups_helper.rb
module CheerupsHelper
end

app/views/cheerups/_cheerup.html.haml
.cheerup
  .cheerup_content
    
    - if cheerup.cheerup_image?
      = link_to image_tag(cheerup.cheerup_image.thumb.url), cheerup.cheerup_image.detail.url
    %p= cheerup.content
    
    .prominence{:id =>"prominence_#{cheerup.id}"} 
      = cheerup.prominence

    .cheerup-show
      = link_to cheerup do
        %i{class:"fa fa-search-plus"}

  .cheerup_poster_info 
    %ul
      - if cheerup.user.profile_picture?
        %li= link_to image_tag(cheerup.user.profile_picture.thumb.url), cheerup.user, class: 'cheerup-avatar'  
      - else
        %li= link_to image_tag(cheerup.user.gravatar_url), cheerup.user, class: 'cheerup-avatar'   

      %li
        = link_to cheerup.user.try(:user_name), cheerup.user
        = "#{time_ago_in_words(cheerup.created_at)} ago"
      
      %li.downvotes{:id =>"downvote_#{cheerup.id}"}
        - if current_user
          - if  session['warden.user.user.key'][0][0].to_i != cheerup.user_id
            = link_to vote_cheerup_path(cheerup, direction: 'down'), method: :put, :id => "downvote_#{cheerup.id}" do
              %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
          - else
            %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
        - else
          %i{class:"fa fa-thumbs-o-down"} #{cheerup.get_downvotes.size}
      %li.upvotes{:id =>"upvote_#{cheerup.id}"}
        - if current_user
          - if  session['warden.user.user.key'][0][0].to_i != cheerup.user_id
            = link_to vote_cheerup_path(cheerup, direction: 'up'), method: :put, :id => "upvote_#{cheerup.id}" do
              %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_upvotes.size}
          - else
            %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_upvotes.size}
        - else
          %i{class:"fa fa-thumbs-o-up"} #{cheerup.get_downvotes.size}
  
  - if current_user
    -if current_user.role?(:admin)
      .cheerup_admin_panel
        %ul
          %li= link_to 'Show', cheerup
          %li= link_to 'Edit', edit_cheerup_path(cheerup)
          %li= link_to 'Delete', cheerup, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/cheerups/_form.html.haml
= form_for(@cheerup) do |f|
  - if @cheerup.errors.any?
    #error_explanation
      %h2
        = pluralize(@cheerup.errors.count, "error")
        prohibited this cheerup from being saved:
      %ul
        - @cheerup.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.text_area :content, rows: 2
  %div
    = f.file_field :cheerup_image
  .actions
    = f.submit

app/views/cheerups/_modal.html.haml
.modal
  %label{:for => "modal-1"}
    .btn.js-btn About Cheerups
  %input#modal-1.modal-state{:type => "checkbox"}/
  .modal-window
    .modal-inner
      %label.modal-close{:for => "modal-1"}
      %h1 Welcome to Cheerups! 
      %p.intro Thanks for visiting Cheerups - the fastest way to spread the cheer
      %p.body.bold Join the Cheerups community: 
      %p.body It’s easy to join Cheerups - you can create an account or simply login with Facebook.
      %p.body.bold How to use: 
      %p.body Cheeringup couldn’t be simpler - just enter your message of 141 characters or less and hit go. You can even upload an image too! To read what the community is saying, you can view random Cheerups or sort them by popularity.
      %p.body.bold Reputation and voting: 
      %p.body Let Cheeruppers know what you think! Click to up or downvote Cheerups and see the most popular messages. The more popular your Cheerups, the higher your Cheerupper status.
      %p.body.bold Privacy: 
      %p.body At Cheerups, information security is very important to us and we will never share your personal details with third parties. However, do remember that messages are public! Please Cheerup responsibly.
      %p.body.bold Code of conduct: 
      %p.body Please respect other Cheeruppers. At Cheerups, we reserve the right to delete your Cheerups or suspend your account if your messages cause offence to other members or are not in keeping with the Cheery nature of our community.
      %p.body.bold Admin:
      %p.body We love Cheerups and hope you do too. However, should you wish to leave, we’ve made things simple for you. You can either deactivate your account, which means we look after your details in case you wish to return, alternatively you can opt to delete it completely. You’ll find these options in your account settings.
     

app/views/cheerups/edit.html.haml
%h1#welcome Edit cheerup
= render 'form'

app/views/cheerups/index.html.haml
%section
  - if current_user 
    - if current_user.role?(:admin) || current_user.role?(:user)
      #create_cheerup
        #new_cheerup_title
          %h6 Create a cheerup
          %i{class:"fa fa-angle-down"}
        .hidden#new_cheerup_form
          = render 'form'
  .button-group#display_methods 
    %label
      = radio_button_tag('button-group', 'random', checked:true)
      = link_to 'Random', display_cheerups_path(display: 'random'), class: 'button-group-item'
    %label
      = radio_button_tag('button-group', 'prominent')
      = link_to 'Popular', display_cheerups_path(display: 'prominent'), class: 'button-group-item'


%main#cheerup_main
  #cheerups
    = render @cheerups

app/views/cheerups/new.html.haml
%h1#welcome New cheerup
= render 'form'

app/views/cheerups/search.html.haml
%h1 Cheerups

- @result.each do |cheerup|
  .cheerup
    %p= cheerup.content
    %p.cheerup_info Posted by: #{cheerup.user.name}
    %p.cheerup_info Time posted: #{time_ago_in_words(cheerup.created_at)} ago
    %br
    %p.cheerup_info  Upvotes #{cheerup.get_upvotes.size}
    %p.cheerup_info  Downvotes #{cheerup.get_downvotes.size}
    %br
    = link_to 'Show', cheerup
    = link_to 'Upvote', vote_cheerup_path(cheerup, direction: 'up'), method: :put, :id => "upvote/#{cheerup.id}"
    = link_to 'Downvote', vote_cheerup_path(cheerup, direction: 'down'), method: :put, :id => "downvote/#{cheerup.id}"
    = link_to 'Edit', edit_cheerup_path(cheerup)
    = link_to 'Delete', cheerup, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/cheerups/show.html.haml
%main#cheerup_main
  #cheerups.show-cheerup-page
    .cheerup
      .cheerup_content
        - if @cheerup.cheerup_image?
          = link_to image_tag(@cheerup.cheerup_image.thumb.url), @cheerup.cheerup_image.detail.url
        %p= @cheerup.content

        .prominence{:id =>"prominence_#{@cheerup.id}"} 
          = @cheerup.prominence

      .cheerup_poster_info 
        %ul
          - if @cheerup.user.profile_picture?
            %li= link_to image_tag(@cheerup.user.profile_picture.thumb.url), @cheerup.user, class: 'cheerup-avatar'  
          - else
            %li= link_to image_tag(@cheerup.user.gravatar_url), @cheerup.user, class: 'cheerup-avatar'   

          %li
            = link_to @cheerup.user.try(:user_name), @cheerup.user
            = "#{time_ago_in_words(@cheerup.created_at)} ago"
          
          %li.downvotes{:id =>"downvote_#{@cheerup.id}"}
            - if current_user
              - if  session['warden.user.user.key'][0][0].to_i != @cheerup.user_id
                = link_to vote_cheerup_path(@cheerup, direction: 'down'), method: :put, :id => "downvote_#{@cheerup.id}" do
                  %i{class:"fa fa-thumbs-o-down"} #{@cheerup.get_downvotes.size}
              - else
                %i{class:"fa fa-thumbs-o-down"} #{@cheerup.get_downvotes.size}
            - else
              %i{class:"fa fa-thumbs-o-down"} #{@cheerup.get_downvotes.size}
          %li.upvotes{:id =>"upvote_#{@cheerup.id}"}
            - if current_user
              - if  session['warden.user.user.key'][0][0].to_i != @cheerup.user_id
                = link_to vote_cheerup_path(@cheerup, direction: 'up'), method: :put, :id => "upvote_#{@cheerup.id}" do
                  %i{class:"fa fa-thumbs-o-up"} #{@cheerup.get_upvotes.size}
              - else
                %i{class:"fa fa-thumbs-o-up"} #{@cheerup.get_upvotes.size}
            - else
              %i{class:"fa fa-thumbs-o-up"} #{@cheerup.get_downvotes.size}
      
        - if current_user
          - if  session['warden.user.user.key'][0][0].to_i == @cheerup.user_id
            .cheerup_admin_panel
              %ul
                %li= link_to 'Edit', edit_cheerup_path(@cheerup)
                %li= link_to 'Delete', @cheerup, method: :delete, data: { confirm: 'Are you sure?' }      
      