config/routes.rb
CheerupsApp::Application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks"}
  devise_for :users
  
  root to: "cheerups#index"
  resources :users
  resources :cheerups

  resources :cheerups do
    member do
      put 'vote/:direction', to: 'cheerups#vote', as: 'vote'
    end

    collection do 
      match 'search'=> "cheerups#search" , via: [:get, :post] , as: :search  
      get 'display/:display', to: 'cheerups#display', as: 'display'
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %meta{charset: 'UTF-8'}
  %head
    %title CheerupsApp
    %link{href:'http://fonts.googleapis.com/css?family=Open+Sans:400,300,700', rel:'stylesheet', type:'text/css'}
    %link{href:'http://fonts.googleapis.com/css?family=Montserrat', rel:'stylesheet', type:'text/css'}
    %link{href:"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", rel:"stylesheet"}

    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

    %header.navigation
    
      = link_to "cheerup.me", root_path, class: 'logo'
      .nav
        = render 'cheerups/modal'
        - if current_user && current_user.role?(:admin)
          = link_to "Users", users_path, class: 'nav-link'
        = link_to "Cheerups", cheerups_path, class: 'nav-link'
        
      .navigation-tools
        .search-bar
          .search-and-submit
            = search_form_for @q, url: search_cheerups_path, html: {method: :post} do |f|
              = f.search_field :content_or_user_name_cont, placeholder: 'Search for cheerup or user...'
              = f.submit 'Search'
        - if user_signed_in?
          #{link_to "#{current_user.name}", user_path(current_user)} #{link_to "Log out", destroy_user_session_path, method: :delete, class: 'sign-up'}
        - else
          = link_to "Sign In", new_user_session_path, class: 'sign-up'
          = link_to "Register", new_user_registration_path, class: 'sign-up'
   
    #site_content
      -if notice
        .notice= notice
      -if alert
        .alert= alert
      #wrapper 
        = yield